files: pyrelay/

repos:
  - repo: https://github.com/PyCQA/autoflake/
    rev: v2.0.0
    hooks:
      - id: autoflake
        language_version: python3
        verbose: true
        args: ["--remove-all-unused-imports", "--recursive", "--remove-unused-variables", "--in-place"]
        exclude: "__init__.py"

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        verbose: true

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        language_version: python3
        verbose: true
        args: ["--recursive", "--apply"]