"""Add deleted at

Revision ID: 5c571f8007b7
Revises: 9b2e8a3aee6b
Create Date: 2023-01-06 18:24:59.708884

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c571f8007b7"
down_revision = "9b2e8a3aee6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "deleted_at")
    # ### end Alembic commands ###
