"""Add tag extras

Revision ID: 9b2e8a3aee6b
Revises: 9ef618136f49
Create Date: 2022-12-31 18:13:55.973739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9b2e8a3aee6b"
down_revision = "9ef618136f49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("extra", sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag", "extra")
    # ### end Alembic commands ###
