"""Add kind

Revision ID: 9ef618136f49
Revises:
Create Date: 2022-12-31 17:08:29.210565

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ef618136f49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("db_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", sa.String(), nullable=True),
        sa.Column("pubkey", sa.String(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("Metadata", "TextNote", "RecommendRelay", name="eventkind"),
            nullable=False,
        ),
        sa.Column("created_at", sa.Integer(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("sig", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("db_id"),
    )
    op.create_index(op.f("ix_event_created_at"), "event", ["created_at"], unique=False)
    op.create_index(op.f("ix_event_kind"), "event", ["kind"], unique=False)
    op.create_index(op.f("ix_event_pubkey"), "event", ["pubkey"], unique=False)
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag")
    op.drop_index(op.f("ix_event_pubkey"), table_name="event")
    op.drop_index(op.f("ix_event_kind"), table_name="event")
    op.drop_index(op.f("ix_event_created_at"), table_name="event")
    op.drop_table("event")
    # ### end Alembic commands ###
